name: 👉 Repo Scan Manual

on:
  workflow_dispatch:
    inputs:
      repository:
        description: <user>/<name> of repository to scan
        required: true

env:
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  REDIS_PORT: ${{ secrets.REDIS_PORT }}
  REDIS_PASS: ${{ secrets.REDIS_PASS }}
  REDIS_USER: ${{ secrets.REDIS_USER }}
  ARCHIVE_REPO_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  typo-scan-exclude-match: '[''typos/**'', ''public/**'']'
  REPORT_ARCHIVE_OWNER: open-source-crawler-test
  REPORT_ARCHIVE_REPO: repo-scan-archive-test
  ARCHIVE_REPO_BRANCH_TARGET: main
  ARCHIVE_COMMIT_EMAIL: commit-bot@gmail.com

jobs:
  repo_scan:
    name: "🕵️‍♂️ Preform manual repository scan"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Cache redis-cli
        uses: actions/cache@v3
        with:
            path: "/usr/bin/redis-cli"
            key: redis-cli-version

      - name: ⬇️ Install redis-cli
        run: |
          if ! command -v redis-cli &> /dev/null
          then
              sudo apt-get install redis
          fi

      - name: Cache bats
        uses: actions/cache@v3
        with:
            path: "/usr/bin/bats"
            key: bats-version
      
      - name: ⬇️ Install bats
        run: |
          if ! command -v bats &> /dev/null
          then
              sudo apt-get install bats
          fi

      - name: "🫣 Parse the input repository"
        run: |
          REPOSITORY="${{ inputs.repository }}"
          echo "repository=$REPOSITORY" >> $GITHUB_ENV

      - name: 📑 Log this repository scan 
        run: |
          chmod -R +rwx scripts
          export REDIS_HOST="${{ env.REDIS_HOST }}"
          export REDIS_PORT"${{ env.REDIS_PORT }}"
          export REDIS_USER="${{ env.REDIS_USER }}"
          export REDIS_PASS="${{ env.REDIS_PASS }}"
          ./scripts/logScanOfRepo.sh ${{ env.repository }}

      - name: "🕵️‍♂️ Preform repository scan"
        if: ${{ env.repository }}
        uses: open-source-crawler-test/repo-scan-test@main
        with:
          repository: ${{ inputs.repository }}
          typo-scan-exclude-match: ${{ env.typo-scan-exclude-match }}
          REPORT_ARCHIVE_OWNER: ${{ env.REPORT_ARCHIVE_OWNER }}
          REPORT_ARCHIVE_REPO: ${{ env.REPORT_ARCHIVE_REPO }}
          ARCHIVE_REPO_BRANCH_TARGET: ${{ env.ARCHIVE_REPO_BRANCH_TARGET }}
          ARCHIVE_COMMIT_EMAIL: ${{ env.ARCHIVE_COMMIT_EMAIL }}
          ARCHIVE_REPO_ACCESS_TOKEN: ${{ env.ARCHIVE_REPO_ACCESS_TOKEN }}
